import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import { ColorModeChoice, ThemeRegistry } from '@/libs/theme/ThemeRegistry';
import '@/app/globals.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Cookieから保存されたカラーモードを取得
  const preColorMode = cookies().get('colorMode')?.value;
  const initColorMode: ColorModeChoice =
    preColorMode === 'light' || preColorMode === 'dark'
      ? preColorMode
      : 'device';

  // 初期表示のカスタムスタイルを適用
  let style: any = {};
  if (['light', 'dark'].includes(initColorMode)) {
    style['--init-background'] = initColorMode === 'dark' ? '#333' : '#fff';
  }
  return (
    <html lang="ja" style={style}>
      <body className={inter.className}>
        <ThemeRegistry initColorMode={initColorMode}>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
